# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Inventory.create( image_url: 'A1-J3.jpg', Designation: 'A1-J3', Cost: 99, Karma_Rating: 'A', Description: 'High mileage but still runs flawlessly. Previously owned by an environmentalist of North American origin and retains its high karma state. Side effects may include a loss of appetite for meat based products and spontaneous tree hugging.', Freshness: 'Super Fresh')
Inventory.create( image_url: 'A1-T5.jpg', Designation: 'A1-T5', Cost: 7, Karma_Rating: 'D', Description: 'Excessive mileage and low karma make this perfect for DIY enthusiasts and bargain hunters. Previously owned by a Banker of Irish origin. Side effects may include shifty eyes and a desire for cocaine.', Freshness: 'Artificially Preserved')
Inventory.create( image_url: 'A1-L6.jpg', Designation: 'A1-L6', Cost: 72, Karma_Rating: 'B-', Description: 'Typical Western mileage albeit with a few...unique features. Previously owned by a screenwriter of Australian origin. Side effects may include : Making up imaginary people and becoming obsessed with their lives and extreme procrastination.', Freshness: 'Like New')
Inventory.create( image_url: 'A1-D8.jpg', Designation: 'A1-D8', Cost: 80, Karma_Rating: 'N/A', Description: 'Minimal mileage. Previous owner of North Korean origin unable to thrive. No side effects involved.', Freshness: 'Super Fresh')
Inventory.create( image_url: 'A1-W9.jpg', Designation: 'A1-W9', Cost: 60, Karma_Rating: 'C++', Description: 'Medium mileage and reasonable karma makes this a perfectly affordable gift. Previously owned by an artist of New Zealand origin. Side effects may include: Debating over the concept of Post-Post modernism and wine snobbery.', Freshness: 'Still Good')
Inventory.create( image_url: 'A1-B4.jpg', Designation: 'A1-B4', Cost: 70, Karma_Rating: 'B', Description: 'High mileage with a few bugs here and there. Previously owned by a Entomologist of British origin. Side Effects may include: Spending a lot of time outdoors and drinking excessive amounts of Earl Grey.', Freshness: 'Still Good')
Inventory.create( image_url: 'A1-R2.jpg', Designation: 'A1-R2', Cost: 78, Karma_Rating: 'B+', Description: 'Favorable mileage and great karma make this a tempting offer. Previously owned by a pilot of South African origin. Side effects may include: Sighing wistfully when birds fly by and the feeling that time is just an illusion of the mind.', Freshness: 'Like New')
Inventory.create( image_url: 'A1-Q1.jpg', Designation: 'A1-Q1', Cost: 65, Karma_Rating: 'C++', Description: 'Low mileage with an acceptable amount of karma. Previously owned by a student of German origin. Side effects may include: Inability to speak coherently with people you find attractive and hormonal imbalance.', Freshness: 'Like New')
Inventory.create( image_url: 'A1-S7.jpg', Designation: 'A1-S7', Cost: 2, Karma_Rating: 'D-', Description: 'High mileage and low karma make this our cheapest option so far. Previously owned by a politician of American origin. Side effects may include: incoherence in written and spoken language and paranoia.', Freshness: 'Artificially Preserved')
Inventory.create( image_url: 'A1-Z0.jpg', Designation: 'A1-Z0', Cost: 28, Karma_Rating: 'C', Description: ' Fair mileage and karma add plenty of affordability to the mix. Previously owned by a Lawyer of Brazilian origin. Side effects may include: Excessive use of legalese and euphemisms and in rare cases drunkly watching Legally Blonde.', Freshness: 'Still Good') 
